In [ ]:
# Data Cleaning
## Step 1: Import Libraries

In [6]:
#导入pandas库，读取csv，数据清洗
import pandas as pd #用pd缩写调用pandas函数

In [ ]:
## Step 2: Load Dataset

In [ ]:
df=pd.read_csv('archive/MutualFund prices - A-E.csv') #变量储存在df dataframe中，自设变量名

In [ ]:
## Step 3: Explore the Dataset

In [7]:
#加display可以展示多行代码
display(df.head())  #查看前几行
display(df.describe()) #描述数据集基本情况 include='all'/'object'分别是统计字符串+数值型/字符串，默认数值

  fund_symbol  price_date  nav_per_share
0       AAAAX  2007-07-31          10.02
1       AAAAX  2007-08-01           9.98
2       AAAAX  2007-08-02          10.01
3       AAAAX  2007-08-03           9.90
4       AAAAX  2007-08-06           9.93

       nav_per_share
count   1.601601e+07
mean    1.791002e+01
std     5.695886e+01
min     0.000000e+00
25%     1.004000e+01
50%     1.224000e+01
75%     1.841000e+01
max     7.662200e+03

In [ ]:
#Data check
df.info() #多少行，多少列，每列类型

df.columns #具体每列

In [9]:
##Step 4: Data problems
df.isnull().sum() #finding missing values
print(round(100*(df.isnull().sum()/len(df.index)),2)) #查看空值在数据集中的百分比

fund_symbol      0.0
price_date       0.0
nav_per_share    0.0
dtype: float64