In [1]:
# Data Cleaning
## Step 1: Import Libraries

In [2]:
#导入pandas库，读取csv，数据清洗
import pandas as pd #用pd缩写调用pandas函数

In [3]:
## Step 2: Load Dataset

In [4]:
df=pd.read_csv('archive/MutualFund prices - A-E.csv') #变量储存在df dataframe中，自设变量名

In [5]:
## Step 3: Explore the Dataset

In [6]:
#加display可以展示多行代码
display(df.head())  #查看前几行
display(df.describe()) #描述数据集基本情况 include='all'/'object'分别是统计字符串+数值型/字符串，默认数值

  fund_symbol  price_date  nav_per_share
0       AAAAX  2007-07-31          10.02
1       AAAAX  2007-08-01           9.98
2       AAAAX  2007-08-02          10.01
3       AAAAX  2007-08-03           9.90
4       AAAAX  2007-08-06           9.93

       nav_per_share
count   1.601601e+07
mean    1.791002e+01
std     5.695886e+01
min     0.000000e+00
25%     1.004000e+01
50%     1.224000e+01
75%     1.841000e+01
max     7.662200e+03

In [7]:
#Data check
df.info() #多少行，多少列，每列类型

df.columns #具体每列

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16016010 entries, 0 to 16016009
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   fund_symbol    object
 1   price_date     object
 2   nav_per_share  float64
dtypes: float64(1), object(2)
memory usage: 366.6+ MB

Index(['fund_symbol', 'price_date', 'nav_per_share'], dtype='object')

In [8]:
##Step 4: Data problems
df.isnull().sum() #finding missing values
print(round(100*(df.isnull().sum()/len(df.index)),2)) #查看空值在数据集中的百分比

fund_symbol      0.0
price_date       0.0
nav_per_share    0.0
dtype: float64

In [10]:
#处理缺失较少的数据
df['fund_symbol'].fillna(0, inplace=True) #把空值替换成数字0
#推荐写法：df['fund_symbol'] = df['fund_symbol'].fillna(0)
df = df.dropna(subset=['nav_per_share']) #删除整行
df.isnull().sum()

C:\Users\JD\AppData\Local\Temp\ipykernel_2312\476444193.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fund_symbol'].fillna(0, inplace=True) #把空值替换成数字0

fund_symbol      0
price_date       0
nav_per_share    0
dtype: int64